application: dive-share
version: 4
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "32d"

builtins:
- deferred: on

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /favicon\.ico
  static_files: stylesheets/flag.png
  upload: stylesheets/flag\.png

- url: /robots\.txt
  static_files: static_files/robots.txt
  upload: static_files/robots\.txt

- url: /apple-touch-icon\.png
  static_files: stylesheets/thumbnail.png
  upload: stylesheets/thumbnail\.png

- url: /pics
  static_dir: pics

- url: /.*
  script: endpoints.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
