application: dive-share
version: 4
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /pics
  static_dir: pics

- url: /.*
  script: endpoints.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
