application: dive-share
version: 4
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /pics
  static_dir: pics

- url: /.*
  script: diveshare.application
